// <auto-generated />
using System;
using Athr.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Athr.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601111748_add_user_roles_permissions")]
    partial class add_user_roles_permissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athr.Domain.BusinessRoles.BusinessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("IdentityId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_business_roles");

                    b.ToTable("businessRoles", (string)null);
                });

            modelBuilder.Entity("Athr.Domain.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("AdminMustHave")
                        .HasColumnType("bit")
                        .HasColumnName("admin_must_have");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("use_case");

                    b.Property<bool>("UserMustHave")
                        .HasColumnType("bit")
                        .HasColumnName("user_must_have");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5853de59-dd78-4252-9125-e69fd8d451b8"),
                            AdminMustHave = false,
                            Name = "instructor.add",
                            Tags = "[\"Business\",\"Instructor\"]",
                            UseCase = "instructor.add",
                            UserMustHave = false,
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("267b1a91-bea9-4720-926e-1bb11925ff70"),
                            AdminMustHave = false,
                            Name = "instructor.index",
                            Tags = "[\"Business\",\"Instructor\"]",
                            UseCase = "instructor.index",
                            UserMustHave = false,
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("c42bb008-d948-4424-9ee2-ba37c13d0182"),
                            AdminMustHave = false,
                            Name = "business.define-allowed-permissions",
                            Tags = "[\"Business\",\"Instructor\",\"Permissions\",\"Security\"]",
                            UseCase = "business.define-allowed-permissions",
                            UserMustHave = false,
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("374ca149-e28d-4230-9c37-760e65d1dfc9"),
                            AdminMustHave = false,
                            Name = "instructor.assign-permissions",
                            Tags = "[\"Business\",\"Instructor\",\"Permissions\",\"Security\"]",
                            UseCase = "instructor.assign-permissions",
                            UserMustHave = false,
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("2e047611-6446-427c-b116-31545bf0d8bd"),
                            AdminMustHave = false,
                            Name = "instructor.edit",
                            Tags = "[\"Business\",\"Instructor\"]",
                            UseCase = "instructor.edit",
                            UserMustHave = false,
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("b43a9f50-73ab-409e-b59c-44c48c4cb0fa"),
                            AdminMustHave = false,
                            Name = "instructor.delete",
                            Tags = "[\"Business\",\"Instructor\"]",
                            UseCase = "instructor.delete",
                            UserMustHave = false,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Athr.Domain.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identity_id");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("identity_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MidName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mid_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Athr.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Athr.Domain.BusinessRoles.BusinessRole", b =>
                {
                    b.OwnsMany("Athr.Domain.BusinessRoles.AllowedPermission", "AllowedPermissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("name");

                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("permission_id");

                            b1.Property<Guid>("business_id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("business_id");

                            b1.HasKey("Id")
                                .HasName("pk_business_allowed_permissions");

                            b1.HasIndex("business_id")
                                .HasDatabaseName("ix_business_allowed_permissions_business_id");

                            b1.ToTable("business_allowed_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("business_id")
                                .HasConstraintName("fk_business_allowed_permissions_business_roles_business_id");
                        });

                    b.Navigation("AllowedPermissions");
                });

            modelBuilder.Entity("Athr.Domain.Users.UserEntity", b =>
                {
                    b.OwnsMany("Athr.Domain.Users.AccountId", "BusinessRoles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("business_id");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_user_businesses");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_user_businesses_user_id");

                            b1.ToTable("user_businesses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_businesses_users_user_id");
                        });

                    b.OwnsMany("Athr.Domain.Users.Authorization.BusinessRolesPermission", "BusinessPermissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<Guid>("BusinessRoleId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("business_role_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("name");

                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("permission_id");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_user_roles_permissions");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_user_roles_permissions_user_id");

                            b1.ToTable("user_roles_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_roles_permissions_users_user_id");
                        });

                    b.Navigation("BusinessPermissions");

                    b.Navigation("BusinessRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
