/**
 * Athr.Api v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryResponse } from './categoryResponse';


export interface CategoryResponsePaginatedList { 
    data: Array<CategoryResponse>;
    total: number;
    currentPage: number;
    perPage: number;
}

